apiVersion: apps/v1
kind: Deployment
metadata:
  name: key
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key
  template:
    metadata:
      labels:
        app: key
    spec:
      containers:
      - image: okteto.dev/key:latest
        name: volue
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/RECIPES-html.zip"
        - name: Vless_UUID
          value: "13629404-477f-456e-9d0a-8f5936513b07"
        - name: Vless_Path
          value: "/13629404-477f-456e-9d0a-8f5936513b07-vless"
        - name: Vmess_UUID
          value: "13629404-477f-456e-9d0a-8f5936513b07"
        - name: Vmess_Path
          value: "/13629404-477f-456e-9d0a-8f5936513b07-vmess"
        - name: Share_Path
          value: "/v2link"
