apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero
  template:
    metadata:
      labels:
        app: zero
    spec:
      containers:
      - image: okteto.dev/zero:latest
        name: zero
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/RECIPES-html.zip"
        - name: Vless_UUID
          value: "9424e8f1-beac-4654-9886-e458d88c6d9a"
        - name: Vless_Path
          value: "/9424e8f1-beac-4654-9886-e458d88c6d9a-vless"
        - name: Vmess_UUID
          value: "9424e8f1-beac-4654-9886-e458d88c6d9a"
        - name: Vmess_Path
          value: "/9424e8f1-beac-4654-9886-e458d88c6d9a0-vmess"
        - name: Share_Path
          value: "/v2link"
