apiVersion: apps/v1
kind: Deployment
metadata:
  name: power
spec:
  replicas: 1
  selector:
    matchLabels:
      app: power
  template:
    metadata:
      labels:
        app: power
    spec:
      containers:
      - image: okteto.dev/power:latest
        name: power
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/Tuxedo-html.zip"
        - name: Vless_UUID
          value: "b52a31d7-91c3-4958-8249-c995baebe72e"
        - name: Vless_Path
          value: "/b52a31d7-91c3-4958-8249-c995baebe72e-vless"
        - name: Vmess_UUID
          value: "b52a31d7-91c3-4958-8249-c995baebe72e"
        - name: Vmess_Path
          value: "/b52a31d7-91c3-4958-8249-c995baebe72e-vmess"
        - name: Share_Path
          value: "/v2link"
