apiVersion: apps/v1
kind: Deployment
metadata:
  name: volue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volue
  template:
    metadata:
      labels:
        app: volue
    spec:
      containers:
      - image: okteto.dev/volue:latest
        name: volue
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/RECIPES-html.zip"
        - name: Vless_UUID
          value: "dbb715c4-9a6d-4c11-b167-739d3de43bd0"
        - name: Vless_Path
          value: "/dbb715c4-9a6d-4c11-b167-739d3de43bd0-vless"
        - name: Vmess_UUID
          value: "dbb715c4-9a6d-4c11-b167-739d3de43bd0"
        - name: Vmess_Path
          value: "/dbb715c4-9a6d-4c11-b167-739d3de43bd0-vmess"
        - name: Share_Path
          value: "/v2link"
